### PR TITLE
[WIP] Issue 3 - Support extension OID 1.3.6.1.4.1.311.21.10

### PR DESCRIPTION
**Pull request by akshithashetty**
Hi, 
I have reached the point shown in screenshot 1 do far and I realized that there is an issue fetching the data. As seen in Screenshot 2 the extensions parameter passed to the getX509Ext method in this case does not have a parsedValue object for OID 1.3.6.1.4.1.311.21.10. Could you please review the code and guide me further?
1)
screenshot from 2019-03-02 23-24-41
2)
screenshot from 2019-03-02 19-36-25

### CODE REVIEW

**Comment by akshithashetty** [comment]
@april could you please guide me through this ?

**Comment by april** [comment]
Are you for sure looking at a cert with this OID?

**Comment by akshithashetty** [comment]
Hi, I have been looking for a cert with OID 1.3.6.1.4.1.311.21.10. I have attached a ss of same in the above comment and numbered it as 2.

**Comment by april** [comment]
Yep, looking at PKIjs, it seems that it does not natively support this OID. You can still see its extnValue, but you would have to parse it yourself. I believe it is a sequence that contains other sequences.

**Comment by akshithashetty** [comment]
Hi, yes right I can see its extnValue, its is an object which consists of blockLength, blockName, idBlock (which is an object), lengthBlock, (which is an object), valueBlock (which is an object), as shown in the screenshot. So, now could you please guide me on what all should we display to provide support ? Thank you. 
Screenshot from 2019-03-15 00-52-12

**Comment by glawrence** [comment]
This PR can be closed as #3 is now resolved with the latest code, which I have tested

**Pull request closed without merging**
