### PR TITLE
[WIP] Support "uploading" a cert chain

### PR DESCRIPTION
**Pull request by monikamaheshwari**
I have added basic html file and context menu for upload certificate. Please let me know if this is ok and what are next steps like on submit event and design of page.

### CODE REVIEW

**Comment by april** [comment]
The layout of the page can always be worked on later, the next steps will be for it to take that uploaded file, parse the certificate, and pass it into the normal code that is used to display the certificate viewer.  :)

**Comment by monikamaheshwari** [comment]
Can you give me the example of certificate file.

**Comment by april** [comment]
Any certificate chain in PEM format should do, as that is most likely what someone would upload.

**Comment by monikamaheshwari** [comment]
Do I need to post or store that certificate otherwise on refresh it will get deleted.

**Comment by april** [comment]
I don't think it's necessary to store it. If we decided we wanted to do that, we could always make a different issue for it.

**Comment by monikamaheshwari** [comment]
Hey it's not clear how I will add that uploaded certificate to normal code as both are separate pages.

**Comment by monikamaheshwari** [comment]
The function parse which you have used converts the rawDER into PEM. But in upload certificate it is already in PEM. So why to parse that certificate?

**Comment by april** [comment]
If it's already in PEM, then you wouldn't need to parse it that way.  :)

**Comment by april** [comment]
This was completed in dd43a1e3488c29e488742690b3a3fd6711304103.

**Pull request closed without merging**
